//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheer.Utilities.GuidGen.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cheer.Utilities.GuidGen.Localization.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 GUID Generator 的本地化字符串。
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .NET Framework Guid Attribute (C#) 的本地化字符串。
        /// </summary>
        internal static string Formatter_CSharpGuidAttributeFormatterName {
            get {
                return ResourceManager.GetString("Formatter_CSharpGuidAttributeFormatterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 name 的本地化字符串。
        /// </summary>
        internal static string Formatter_DefineGuidFormatter_ObjectName {
            get {
                return ResourceManager.GetString("Formatter_DefineGuidFormatter_ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DEFINE_GUID(...) 的本地化字符串。
        /// </summary>
        internal static string Formatter_DefineGuidFormatterName {
            get {
                return ResourceManager.GetString("Formatter_DefineGuidFormatterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 class_name 的本地化字符串。
        /// </summary>
        internal static string Formatter_OleCreateGuidFormatter_ClassName {
            get {
                return ResourceManager.GetString("Formatter_OleCreateGuidFormatter_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 external_name 的本地化字符串。
        /// </summary>
        internal static string Formatter_OleCreateGuidFormatter_ExternalName {
            get {
                return ResourceManager.GetString("Formatter_OleCreateGuidFormatter_ExternalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IMPLEMENT_OLECREATE(...) 的本地化字符串。
        /// </summary>
        internal static string Formatter_OleCreateGuidFormatterName {
            get {
                return ResourceManager.GetString("Formatter_OleCreateGuidFormatterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registry Format ({xxxxxxxx-xxxx ... xxxx}) 的本地化字符串。
        /// </summary>
        internal static string Formatter_RegistryGuidFormatterName {
            get {
                return ResourceManager.GetString("Formatter_RegistryGuidFormatterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 name 的本地化字符串。
        /// </summary>
        internal static string Formatter_StaticConstGuidFormatter_Name {
            get {
                return ResourceManager.GetString("Formatter_StaticConstGuidFormatter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 static const struct GUID = { ... } 的本地化字符串。
        /// </summary>
        internal static string Formatter_StaticConstGuidFormatterName {
            get {
                return ResourceManager.GetString("Formatter_StaticConstGuidFormatterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .NET Framework Guid Attribute (Visual Basic) 的本地化字符串。
        /// </summary>
        internal static string Formatter_VBGuidAttributeFormatterName {
            get {
                return ResourceManager.GetString("Formatter_VBGuidAttributeFormatterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy A&amp;ll 的本地化字符串。
        /// </summary>
        internal static string MainForm_CopyAllToolStipMenuItemText {
            get {
                return ResourceManager.GetString("MainForm_CopyAllToolStipMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Copy 的本地化字符串。
        /// </summary>
        internal static string MainForm_CopyButtonText {
            get {
                return ResourceManager.GetString("MainForm_CopyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Copy 的本地化字符串。
        /// </summary>
        internal static string MainForm_CopyToolStripMenuItemText {
            get {
                return ResourceManager.GetString("MainForm_CopyToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GUID Format 的本地化字符串。
        /// </summary>
        internal static string MainForm_FormatGroupBoxText {
            get {
                return ResourceManager.GetString("MainForm_FormatGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;New GUID 的本地化字符串。
        /// </summary>
        internal static string MainForm_NewGuidButtonText {
            get {
                return ResourceManager.GetString("MainForm_NewGuidButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Results 的本地化字符串。
        /// </summary>
        internal static string MainForm_ResultsGroupBoxText {
            get {
                return ResourceManager.GetString("MainForm_ResultsGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select &amp;All 的本地化字符串。
        /// </summary>
        internal static string MainForm_SelAllToolStripMenuItemText {
            get {
                return ResourceManager.GetString("MainForm_SelAllToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Top Most 的本地化字符串。
        /// </summary>
        internal static string MainForm_TopMostCheckBoxText {
            get {
                return ResourceManager.GetString("MainForm_TopMostCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep this window stay on top of all other windows. 的本地化字符串。
        /// </summary>
        internal static string MainForm_TopMostCheckBoxToolTip {
            get {
                return ResourceManager.GetString("MainForm_TopMostCheckBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose from one of the following GUID format options, then press &apos;Copy&apos; to copy the results to the system clipboard.
        ///Press &apos;New GUID&apos; to create a new GUID. 的本地化字符串。
        /// </summary>
        internal static string MainForm_UsageLabelText {
            get {
                return ResourceManager.GetString("MainForm_UsageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Word &amp;Wrap 的本地化字符串。
        /// </summary>
        internal static string MainForm_WordWrapToolStripMenuItemText {
            get {
                return ResourceManager.GetString("MainForm_WordWrapToolStripMenuItemText", resourceCulture);
            }
        }
    }
}
